### ISSUE TITLE
error when running from the host

### ISSUE THREAD

**Issue by jahwanoh** [jetsonhacks/gpuGraphTX#5]
I ran it from the host by 
python3 gpuGraph.py $JETSON@$IP
rsync was installed, but I have this error.
do you have any suggestion?

```
Traceback (most recent call last):
  File "/home/bepro/.local/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3.py", line 88, in _on_timer
    TimerBase._on_timer(self)
  File "/home/bepro/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1205, in _on_timer
    ret = func(*args, **kwargs)
  File "/home/bepro/.local/lib/python3.6/site-packages/matplotlib/animation.py", line 1449, in _step
    still_going = Animation._step(self, *args)
  File "/home/bepro/.local/lib/python3.6/site-packages/matplotlib/animation.py", line 1169, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/home/bepro/.local/lib/python3.6/site-packages/matplotlib/animation.py", line 1188, in _draw_next_frame
    self._draw_frame(framedata)
  File "/home/bepro/.local/lib/python3.6/site-packages/matplotlib/animation.py", line 1766, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "gpuGraph.py", line 75, in updateGraph
    fileData = subprocess.check_output(cmd.split(" ")).decode("utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sshpass': 'sshpass'

```

**Comment by bitbrain-za** [comment]
`sudo apt install sshpass`
